dataviz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('viz/',include('viz.urls')),
    path('', include('viz.urls')),
]

viz/urls.py
from django.urls import path, include
from . import views

app_name = 'viz'
## module san pham
urlpatterns = [
    path('', views.index, name='index'),
    path('them_nhom_hang/', views.them_nhom_hang, name='them_nhom_hang'),
    path('them_mat_hang/', views.them_mat_hang, name='them_mat_hang'),
    path('update_nhom_hang/<str:ma_nhom_hang>/', views.update_nhom_hang, name='update_nhom_hang'),
    path('update_mat_hang/<str:ma_mat_hang>', views.update_mat_hang, name='update_mat_hang'),
    path('list_nhom_hang/', views.list_nhom_hang, name='list_nhom_hang'),
    path('list_mat_hang/', views.list_mat_hang, name='list_mat_hang'),
    path('delete_nhom_hang/<str:ma_nhom_hang>/', views.delete_nhom_hang, name='delete_nhom_hang'),
    path('delete_mat_hang/<str:ma_mat_hang>/', views.delete_mat_hang, name='delete_mat_hang'),
]
## module khach hang
urlpatterns += [
    path('them_khach_hang/', views.them_khach_hang, name='them_khach_hang'),
    path('list_khach_hang/', views.list_khach_hang, name='list_khach_hang'),
    path('update_khach_hang/<str:ma_khach_hang>/', views.update_khach_hang, name='update_khach_hang'),
    path('delete_khach_hang/<str:ma_khach_hang>/', views.delete_khach_hang, name='delete_khach_hang'),
    path('them_pkkh/', views.them_pkkh, name='them_pkkh'),
    path('list_pkkh/', views.list_pkkh, name='list_pkkh'),
    path('update_pkkh/<str:ma_pkkh>/', views.update_pkkh, name='update_pkkh'),
    path('delete_pkkh/<str:ma_pkkh>/', views.delete_pkkh, name='delete_pkkh'),
]

## module don hang
urlpatterns += [
    path('them_don_hang/', views.them_don_hang, name='them_don_hang'),
    path('list_don_hang/', views.list_don_hang, name='list_don_hang'),
    # path('update_don_hang/<str:ma_don_hang>/', views.update_don_hang, name='update_don_hang'),
    path('delete_don_hang/<str:ma_don_hang>/', views.delete_don_hang, name='delete_don_hang'),
]

## file upload func
urlpatterns += [
    path('upload_don_hang/', views.upload_don_hang, name='upload_don_hang'),
    path('upload_nhom_hang/', views.upload_nhom_hang, name='upload_nhom_hang'),
    path('upload_mat_hang/', views.upload_mat_hang, name='upload_mat_hang'),
    path('upload_khach_hang/', views.upload_khach_hang, name='upload_khach_hang'),
    path('upload_pkkh/', views.upload_pkkh, name='upload_pkkh'),
]


## module thong ke 
urlpatterns += [
    path('detail_khach_hang/<str:ma_khach_hang>', views.detail_khach_hang, name='detail_khach_hang'),
    path('detail_mat_hang/<str:ma_mat_hang>', views.detail_mat_hang, name='detail_mat_hang'),
]
## tao don hang voi fetchapi
urlpatterns += [
    path('get_khach_hang_info/<str:ma_khach_hang>/', views.get_khach_hang_info, name='get_khach_hang_info'),
    path('get_mat_hang_info/<str:ma_mat_hang>/', views.get_mat_hang_info, name='get_mat_hang_info'),
]

## temp xóa đơn hàng :D
urlpatterns += [
    path('xoa_het/', views.delete_all_don_hang, name='xoa_het'),
]

## visualization page
urlpatterns += [
    path('visualization/', views.visualization, name='visualization')
]

viz/models.py
from django.db import models
import random, datetime
from django.utils import timezone
import pandas as pd
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

def generate_id(cls, field_name, prefix, num_length): 
    """Tạo ID tự động với prefix và độ dài cố định"""        
    while True:
        num_part = str(random.randint(0, 10**num_length - 1)).zfill(num_length)
        new_id = prefix + num_part
        if not cls.objects.filter(**{field_name: new_id}).exists():
            return new_id

class NhomHang(models.Model):
    ma_nhom_hang = models.CharField(primary_key=True, max_length=8, unique=True)
    ten_nhom_hang = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = "Nhóm hàng"

    def __str__(self):
        return f"{self.ma_nhom_hang}"    

class MatHang(models.Model):    
    ma_mat_hang = models.CharField(primary_key=True, max_length=8, unique=True)
    ten_mat_hang = models.CharField(max_length=100)
    ma_nhom_hang = models.ForeignKey(NhomHang, on_delete=models.CASCADE)
    don_gia = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "Mặt hàng"                    
    
    def __str__(self):
        return self.ten_mat_hang     

class PhanKhucKhachHang(models.Model):
    ma_pkkh = models.CharField(primary_key=True, max_length=10, unique=True)
    mo_ta_pkkh = models.TextField()

    class Meta:
        verbose_name_plural = "Phân khúc khách hàng"

    def __str__(self):
        return self.ma_pkkh

class KhachHang(models.Model):
    ma_khach_hang = models.CharField(primary_key=True, max_length=8, unique=True)
    ten_khach_hang = models.CharField(max_length=100)
    phan_khuc = models.ForeignKey(PhanKhucKhachHang, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Khách hàng"
        
    def __str__(self):
        return self.ten_khach_hang
        
class DonHang(models.Model):
    id = models.AutoField(primary_key=True)
    thoi_gian_tao_don = models.DateTimeField(default=timezone.now)
    ma_don_hang = models.CharField(max_length=10)
    ma_khach_hang = models.CharField(max_length=9)
    khach_hang = models.TextField()
    ma_pkkh = models.CharField(max_length=3)
    mo_ta_pkkh = models.TextField()
    ma_nhom_hang = models.CharField(max_length=4)
    ten_nhom_hang = models.TextField()
    ma_mat_hang = models.CharField(max_length=8)
    ten_mat_hang  = models.TextField()
    don_gia = models.IntegerField()         
    so_luong = models.IntegerField()
    thanh_tien = models.IntegerField()
    class Meta:
        verbose_name_plural = "Đơn hàng"

    def save(self, *args, **kwargs):
        self.thanh_tien = self.so_luong * MatHang.objects.get(ma_mat_hang=self.ma_mat_hang).don_gia
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f"{self.ma_don_hang} - {self.ma_mat_hang} - SL: {self.so_luong} - Tổng: {self.thanh_tien}"
    

class Chat(models.Model):
    sender = models.CharField(max_length=100)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

viz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from .models import MatHang, NhomHang, KhachHang, DonHang, PhanKhucKhachHang, generate_id 
import pandas as pd
from django.contrib import messages
from django.http import JsonResponse
import json

# Create your views here.
def index(request):
    return render(request, 'index.html')

def them_nhom_hang(request):
    if request.method == "POST":
        ma_nhom_hang = request.POST.get('ma_nhom_hang')
        ten_nhom_hang = request.POST.get('ten_nhom_hang')
        mo_ta = request.POST.get('mo_ta')
        # Tạo một đối tượng và lưu vào database
        NhomHang.objects.create(
            ma_nhom_hang = ma_nhom_hang,
            ten_nhom_hang = ten_nhom_hang,
            mo_ta = mo_ta
        )
        return redirect('viz:list_nhom_hang')  # Chuyển hướng sau khi lưu
    return render(request, 'shop/nhom_hang/them_nhom_hang.html')

def them_mat_hang(request):
    list_nhom_hang = NhomHang.objects.all()
    if request.method == "POST":
        ten_mat_hang = request.POST.get('ten_mat_hang')
        ma_nhom_hang = request.POST.get('ma_nhom_hang')
        don_gia = request.POST.get('don_gia')
        mo_ta = request.POST.get('mo_ta')
        ma_mat_hang = generate_id(MatHang, 'ma_mat_hang', ma_nhom_hang, 2)
        # Tạo một đối tượng và lưu vào database
        MatHang.objects.create(
            ma_mat_hang = ma_mat_hang,
            ten_mat_hang = ten_mat_hang,
            ma_nhom_hang = NhomHang.objects.get(ma_nhom_hang=ma_nhom_hang),
            don_gia = don_gia,
            mo_ta = mo_ta
        )
        return redirect('viz:list_mat_hang')
    return render(request, 'shop/mat_hang/them_mat_hang.html', {'list_nhom_hang': list_nhom_hang})

def update_nhom_hang(request, ma_nhom_hang):
        # Tìm nhóm hàng theo mã, nếu không có thì trả về 404
    nhom_hang = get_object_or_404(NhomHang, ma_nhom_hang=ma_nhom_hang)
    if request.method == "POST":
        ten_nhom_hang = request.POST.get('ten_nhom_hang')
        mo_ta = request.POST.get('mo_ta')
            # Cập nhật dữ liệu
        nhom_hang.ten_nhom_hang = ten_nhom_hang
        nhom_hang.mo_ta = mo_ta
        nhom_hang.save()
        return redirect('viz:list_nhom_hang') 
    return render(request, 'shop/nhom_hang/update_nhom_hang.html', {'nhom_hang': nhom_hang})

def update_mat_hang(request, ma_mat_hang):
    mat_hang = get_object_or_404(MatHang, ma_mat_hang=ma_mat_hang)
    nhom_hang = NhomHang.objects.all()
    if request.method == "POST":
        ten_mat_hang = request.POST.get('ten_mat_hang')
        ma_nhom_hang = request.POST.get('ma_nhom_hang')
        don_gia = request.POST.get('don_gia')
        mat_hang.ma_nhom_hang = NhomHang.objects.get(ma_nhom_hang=ma_nhom_hang)
        mat_hang.ten_mat_hang = ten_mat_hang
        if request.POST.get('don_gia'):
            mat_hang.don_gia = don_gia
        mat_hang.save()
        return redirect('viz:list_mat_hang')
    return render(request, 'shop/mat_hang/update_mat_hang.html', {'mat_hang': mat_hang, 'nhom_hang': nhom_hang}) 

def list_nhom_hang(request):
    list_nhom_hang = NhomHang.objects.all()
    return render(request, 'shop/nhom_hang/list_nhom_hang.html', {'list_nhom_hang': list_nhom_hang})

def list_mat_hang(request):
    list_mat_hang = MatHang.objects.all()
    return render(request, 'shop/mat_hang/list_mat_hang.html', {'list_mat_hang': list_mat_hang})

def delete_nhom_hang(request, ma_nhom_hang):
    nhom_hang = get_object_or_404(NhomHang, ma_nhom_hang=ma_nhom_hang)
    if request.method == "POST":
        nhom_hang = get_object_or_404(NhomHang, ma_nhom_hang=ma_nhom_hang)
        nhom_hang.delete()
        return redirect('viz:list_nhom_hang')
    return render(request, 'shop/nhom_hang/delete_nhom_hang.html', {'nhom_hang': nhom_hang})

def delete_mat_hang(request, ma_mat_hang):
    mat_hang = get_object_or_404(MatHang, ma_mat_hang=ma_mat_hang)
    if request.method == "POST":
        mat_hang.delete()
        return redirect('viz:list_mat_hang')
    return render(request, 'shop/mat_hang/delete_mat_hang.html', {'mat_hang': mat_hang})

def them_pkkh(request):
    if request.method == "POST":
        ma_pkkh = request.POST.get('ma_pkkh')
        mo_ta_pkkh = request.POST.get('mo_ta_pkkh')
        # Tạo một đối tượng và lưu vào database
        PhanKhucKhachHang.objects.create(
            ma_pkkh = ma_pkkh,
            mo_ta_pkkh = mo_ta_pkkh
        )
        return redirect('viz:list_pkkh')
    return render(request, 'shop/pkkh/them_pkkh.html')

def list_pkkh(request):
    list_pkkh = PhanKhucKhachHang.objects.all()
    return render(request, 'shop/pkkh/list_pkkh.html', {'list_pkkh': list_pkkh})

def update_pkkh(request, ma_pkkh):
    pkkh = get_object_or_404(PhanKhucKhachHang, ma_pkkh=ma_pkkh)
    if request.method == "POST":
        mo_ta_pkkh = request.POST.get('mo_ta_pkkh')
        pkkh.mo_ta_pkkh = mo_ta_pkkh
        pkkh.save()
        return redirect('viz:list_pkkh')
    return render(request, 'shop/pkkh/update_pkkh.html', {'pkkh': pkkh})

def delete_pkkh(request, ma_pkkh):
    pkkh = get_object_or_404(PhanKhucKhachHang, ma_pkkh=ma_pkkh)
    if request.method == "POST":
        pkkh.delete()
        return redirect('viz:list_pkkh')
    return render(request, 'shop/pkkh/delete_pkkh.html', {'pkkh': pkkh})

def them_khach_hang(request):
    list_pkkh = PhanKhucKhachHang.objects.all()
    if request.method == "POST":
        ma_khach_hang = generate_id(KhachHang, 'ma_khach_hang', 'CUZ', 5)
        ten_khach_hang = request.POST.get('ten_khach_hang')
        phan_khuc = request.POST.get('phan_khuc')
        # Tạo một đối tượng và lưu vào database
        KhachHang.objects.create(
            ma_khach_hang = ma_khach_hang,
            ten_khach_hang = ten_khach_hang,
            phan_khuc = PhanKhucKhachHang.objects.get(ma_pkkh=phan_khuc)
        )
        return redirect('viz:list_khach_hang')
    return render(request, 'shop/khach_hang/them_khach_hang.html', {'list_pkkh': list_pkkh})

def list_khach_hang(request):
    list_khach_hang = KhachHang.objects.all()
    return render(request, 'shop/khach_hang/list_khach_hang.html', {'list_khach_hang': list_khach_hang})

def update_khach_hang(request, ma_khach_hang):
    khach_hang = get_object_or_404(KhachHang, ma_khach_hang=ma_khach_hang)
    list_pkkh = PhanKhucKhachHang.objects.all()
    if request.method == "POST":
        ten_khach_hang = request.POST.get('ten_khach_hang')
        phan_khuc = request.POST.get('phan_khuc')
        khach_hang.ten_khach_hang = ten_khach_hang
        khach_hang.phan_khuc = PhanKhucKhachHang.objects.get(ma_pkkh=phan_khuc)
        khach_hang.save()
        return redirect('viz:list_khach_hang')
    return render(request, 'shop/khach_hang/update_khach_hang.html', {'khach_hang': khach_hang, 'list_pkkh': list_pkkh})

def delete_khach_hang(request, ma_khach_hang):
    khach_hang = get_object_or_404(KhachHang, ma_khach_hang=ma_khach_hang)
    if request.method == "POST":
        khach_hang.delete()
        return redirect('viz:list_khach_hang')
    return render(request, 'shop/khach_hang/delete_khach_hang.html', {'khach_hang': khach_hang})

# def them_don_hang(request):
#     list_khach_hang = KhachHang.objects.all()
#     list_mat_hang = MatHang.objects.all()
    
#     selected_khach_hang = None
#     selected_mat_hang = None

#     if request.method == "POST":
#         ma_khach_hang = request.POST.get('ma_khach_hang', '')
#         ma_mat_hang = request.POST.get('ma_mat_hang', '')
#         so_luong = request.POST.get('so_luong', '')

#         # Lấy thông tin khách hàng nếu đã chọn
#         if ma_khach_hang:
#             try:
#                 selected_khach_hang = KhachHang.objects.get(ma_khach_hang=ma_khach_hang)
#             except KhachHang.DoesNotExist:
#                 selected_khach_hang = None

#         # Lấy thông tin mặt hàng nếu đã chọn
#         if ma_mat_hang:
#             try:
#                 selected_mat_hang = MatHang.objects.get(ma_mat_hang=ma_mat_hang)
#             except MatHang.DoesNotExist:
#                 selected_mat_hang = None

#         # Nếu đủ thông tin, thêm đơn hàng vào database
#         if selected_khach_hang and selected_mat_hang and so_luong:
#             ma_don_hang = generate_id(DonHang, 'ma_don_hang', 'ORD', 5)
#             DonHang.objects.create(
#                 ma_don_hang=ma_don_hang,
#                 ma_khach_hang=selected_khach_hang.ma_khach_hang,
#                 khach_hang=selected_khach_hang.ten_khach_hang,
#                 ma_pkkh=selected_khach_hang.phan_khuc.ma_pkkh,
#                 mo_ta_pkkh=selected_khach_hang.phan_khuc.mo_ta_pkkh,
#                 ma_nhom_hang=selected_mat_hang.ma_nhom_hang.ma_nhom_hang,
#                 ten_nhom_hang=selected_mat_hang.ma_nhom_hang.ten_nhom_hang,
#                 ma_mat_hang=selected_mat_hang.ma_mat_hang,
#                 ten_mat_hang=selected_mat_hang.ten_mat_hang,
#                 don_gia=int(selected_mat_hang.don_gia),
#                 so_luong=int(so_luong),
#                 thanh_tien= int(selected_mat_hang.don_gia) * int(so_luong)
#             )
#             return redirect('viz:list_don_hang')

#     return render(request, 'shop/don_hang/them_don_hang.html', {
#         'list_khach_hang': list_khach_hang,
#         'list_mat_hang': list_mat_hang,
#         'selected_khach_hang': selected_khach_hang,
#         'selected_mat_hang': selected_mat_hang
#     })



# def list_don_hang(request):
#     list_don_hang = DonHang.objects.all()
#     return render(request, 'shop/don_hang/list_don_hang.html', {'list_don_hang': list_don_hang})

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Thêm import này vào đầu file

def list_don_hang(request):
    # Lấy tất cả đơn hàng và sắp xếp theo thời gian mới nhất
    all_don_hang = DonHang.objects.all().order_by('-thoi_gian_tao_don')
    
    # Pagination - 25 items per page
    paginator = Paginator(all_don_hang, 25)

viz/templates/shop/don_hang/delete_don_hang.html
{% extends 'layout.html' %}

{% block content %}
<h2>Xác nhận xóa</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Xóa</button>
    <a href="{% url 'viz:list_don_hang' %}" class="btn btn-secondary">Hủy</a>
</form>
{% endblock %}

viz/templates/shop/don_hang/list_don_hang.html
{% extends 'layout.html' %}
{% load humanize %}

{% block content %}
<h2 class="text-center mb-4">Danh Sách Đơn Hàng</h2>

<div class="text-center mb-4">
    <a class="btn btn-primary me-3" href="{% url 'viz:them_don_hang' %}">
        Thêm Đơn Hàng
    </a>
    <a class="btn btn-success" href="{% url 'viz:upload_don_hang' %}">
        Upload Đơn Hàng
    </a>
</div>

<!-- Pagination info -->
<div class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">
        Hiển thị {{ list_don_hang.start_index }} - {{ list_don_hang.end_index }} 
        trong tổng số {{ list_don_hang.paginator.count }} đơn hàng
    </span>
    <span class="badge bg-info">Trang {{ list_don_hang.number }} / {{ list_don_hang.paginator.num_pages }}</span>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead >
            <tr>
                <th>Mã Đơn Hàng</th>
                <th>Thời Gian Tạo</th>
                <th>Khách Hàng</th>
                <th>Mặt Hàng</th>
                <th>SL</th>
                <th>Thành Tiền</th>
            </tr>
        </thead>
        <tbody>
            {% for don_hang in list_don_hang %}
            <tr>
                <td><code>{{ don_hang.ma_don_hang }}</code></td>
                <td>{{ don_hang.thoi_gian_tao_don|date:"d/m/Y H:i" }}</td>
                <td>{{ don_hang.khach_hang }}</td>
                <td>{{ don_hang.ten_mat_hang }}</td>
                <td><span>{{ don_hang.so_luong }}</span></td>
                <td><strong>{{ don_hang.thanh_tien|intcomma }} VND</strong></td>
                
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="text-center text-muted">
                    <em>Chưa có đơn hàng nào</em>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Pagination controls -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if list_don_hang.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo; Đầu</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ list_don_hang.previous_page_number }}">‹ Trước</a>
            </li>
        {% endif %}

        {% for num in list_don_hang.paginator.page_range %}
            {% if list_don_hang.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > list_don_hang.number|add:'-3' and num < list_don_hang.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if list_don_hang.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ list_don_hang.next_page_number }}">Sau ›</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ list_don_hang.paginator.num_pages }}">Cuối &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

viz/templates/shop/don_hang/them_don_hang.html
{% extends 'layout.html' %}
{% block content %}
<h2>Thêm đơn hàng</h2>
<form id="orderform" method="POST">
    {% csrf_token %}
    
    <label for="ma_khach_hang">Mã Khách Hàng:</label>
    <select id="ma_khach_hang" name="ma_khach_hang" class="form-control">
        <option value="">-- Chọn khách hàng --</option>
        {% for kh in list_khach_hang %}
            <option value="{{ kh.ma_khach_hang }}">{{ kh.ma_khach_hang }} - {{ kh.ten_khach_hang }}</option>
        {% endfor %}
    </select>

    <label for="ten_khach_hang">Tên Khách Hàng:</label>
    <input type="text" id="ten_khach_hang" name="ten_khach_hang" class="form-control" readonly>

    <label for="ma_pkkh">Mã Phân Khúc:</label>
    <input type="text" id="ma_pkkh" name="ma_pkkh" class="form-control" readonly>

    <label for="mo_ta_pkkh">Mô Tả Phân Khúc:</label>
    <input type="text" id="mo_ta_pkkh" name="mo_ta_pkkh" class="form-control" readonly>

    <label for="ma_mat_hang">Mã Mặt Hàng:</label>
    <select id="ma_mat_hang" name="ma_mat_hang" class="form-control">
        <option value="">-- Chọn mặt hàng --</option>
        {% for mh in list_mat_hang %}
            <option value="{{ mh.ma_mat_hang }}">{{ mh.ma_mat_hang }} - {{ mh.ten_mat_hang }}</option>
        {% endfor %}
    </select>

    <label for="ten_mat_hang">Tên Mặt Hàng:</label>
    <input type="text" id="ten_mat_hang" name="ten_mat_hang" class="form-control">

    <label for="don_gia">Đơn Giá:</label>
    <input type="text" id="don_gia" name="don_gia" class="form-control" >

    <label for="ma_nhom_hang">Mã Nhóm Hàng:</label>
    <input type="text" id="ma_nhom_hang" name="ma_nhom_hang" class="form-control" >

    <label for="ten_nhom_hang">Tên Nhóm Hàng:</label>
    <input type="text" id="ten_nhom_hang" name="ten_nhom_hang" class="form-control">

    <label for="so_luong">Số Lượng:</label>
    <input type="number" id="so_luong" name="so_luong" class="form-control" required>

    <br>
    
    <button type="submit" class="btn btn-primary">Thêm Đơn Hàng</button>
</form>

<script>
    document.getElementById('ma_khach_hang').addEventListener('change', function() {
        const maKhachHang = this.value;
        if (maKhachHang) {
            fetch(`/viz/get_khach_hang_info/${maKhachHang}/`)
                .then(response => response.json())
                .then(data => {
                    document.getElementById('ten_khach_hang').value = data.ten_khach_hang;
                    document.getElementById('ma_pkkh').value = data.ma_pkkh;
                    document.getElementById('mo_ta_pkkh').value = data.mo_ta_pkkh;
                })
                .catch(error => console.error(error));
        } else {
            document.getElementById('ten_khach_hang').value = '';
            document.getElementById('ma_pkkh').value = '';
            document.getElementById('mo_ta_pkkh').value = '';
        }
    });
    
    document.getElementById('ma_mat_hang').addEventListener('change', function() {
        const maMatHang = this.value;
        if (maMatHang) {
            fetch(`/viz/get_mat_hang_info/${maMatHang}/`)
                .then(response => response.json())
                .then(data => {
                    document.getElementById('ten_mat_hang').value = data.ten_mat_hang;
                    document.getElementById('don_gia').value = data.don_gia;
                    document.getElementById('ma_nhom_hang').value = data.ma_nhom_hang;
                    document.getElementById('ten_nhom_hang').value = data.ten_nhom_hang;
                })
                .catch(error => console.error(error));
        } else {
            document.getElementById('ten_mat_hang').value = '';
            document.getElementById('don_gia').value = '';
            document.getElementById('ma_nhom_hang').value = '';
            document.getElementById('ten_nhom_hang').value = '';
        }
    });
    </script>

{% endblock %}